### ISSUE TITLE
New release of Orb fixes an important bug

### ISSUE THREAD

**Issue by benrhodes26** [usnistgov/chipsff#8]
Hi there! Thanks for the great work. It's always exciting to see these types of comprehensive benchmarks 💯 

Just wanted to flag that we just solved a significant bug in the latest release of Orb: https://github.com/orbital-materials/orb-models/releases

Basically, we were erroneously expecting users to handle unit-cell-wrapping. This is now handled by our featurization code.

I haven't checked your code to know the impacts of this, but it seems plausible it could have impacted the amorphous silica MD (amongst other things).

Keep up the great work!

**Comment by wines1** [comment]
Hi Ben,

Thanks so much for the kind words about our work. Thanks for bringing this to our attention, I have upgraded Orb to v4.1.0 and re-ran the amorphous Silicon MD calculation (just a quick test, not a production run yet). It seems that fixing this bug has eliminated the previous errors for the melt/quench MD of a-Si. I am currently running a production run calculation for this system and will re-run other properties to see if other results change. We will update the preprint on arXiv and benchmarks in the JARVIS-Leaderboard with updated results once these calculations are done. Once these updates are made I will close this issue. Thanks again!

**Comment by benrhodes26** [comment]
Incredible. Thank you so much!

**Comment by wines1** [comment]
I just updated the preprint on arXiv, the new version should be live by Tuesday. Thanks again for reaching out and letting us know about the bug fix. This seemed to have fixed the issues for amorphous structures and interfaces. These kinds of interactions are great and move the field forward! Keep up the great work at Orbital Materials! Closing this issue for now, if anything else arises please don't hesitate to reach out.
